# Generated by Django 5.2.7 on 2025-12-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название тренажера')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('category', models.CharField(choices=[('memory', 'Память'), ('attention', 'Внимание'), ('logic', 'Логика'), ('creativity', 'Творчество'), ('math', 'Математика'), ('language', 'Язык')], max_length=50, verbose_name='Категория')),
                ('difficulty', models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Уровень сложности')),
                ('age_min', models.IntegerField(default=1, verbose_name='Минимальный возраст')),
                ('age_max', models.IntegerField(default=18, verbose_name='Максимальный возраст')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Иконка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='trainers/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тренажер',
                'verbose_name_plural': 'Тренажеры',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['slug'], name='api_trainer_slug_9e61cf_idx'), models.Index(fields=['category'], name='api_trainer_categor_7eac55_idx'), models.Index(fields=['is_active'], name='api_trainer_is_acti_c59d98_idx')],
            },
        ),
    ]
